const CartType = {
  TOGGLE_HIDDEN_DROPDOWN: "TOGGLE_HIDDEN_DROPDOWN",
  ADD_CART_ITEM: "ADD_CART_ITEM",
  REMOVE_ITEM_FROM_CHECKOUT: "REMOVE_ITEM_FROM_CHECKOUT",
  REMOVE_CART_ITEM_CHECKOUT: "REMOVE_CART_ITEM_CHECKOUT",
};

export default CartType;
